### ISSUE TITLE
Missing argument in initialize

### ISSUE THREAD

**Issue by Matt-Yorkley** [Vasfed/csso-rails#30] opened 2017-07-30 18:50 UTC
I get a fatal error using the csso gem:

![screenshot from 2017-07-30 19-38-29](https://user-images.githubusercontent.com/9029026/28756051-3b4fc1d2-755f-11e7-89de-f181d4a3ac12.png)

I'm using Rails 3.2 and including csso with:

`config.assets.css_compressor = :csso`

**Comment by Matt-Yorkley** [comment] 2017-08-03 08:07
It looks like `Compressor#initialize` is being called without the `path` argument?

**Comment by Vasfed** [comment] 2017-08-03 16:00
Will look into it today, appears like initialisation for rails-3.2 is broken

**Comment by Vasfed** [comment] 2017-08-03 18:40
Fix will be released in 0.8.1 (now waiting for CI)

**Comment by Matt-Yorkley** [comment] 2017-08-04 12:27
Now I'm getting this error instead: 

![screenshot from 2017-08-04 13-25-07](https://user-images.githubusercontent.com/9029026/28968582-877e0ab6-7918-11e7-96b4-9940888a2055.png)

Should I be adding anything else in the config?

**Comment by Vasfed** [comment] 2017-08-04 13:39
@Matt-Yorkley cannot reproduce this, which versions of sass and sass-rails are you using?
It may be related to https://github.com/rails/sass-rails/issues/111
Tried skeleton app on rails (3.2.21) + sass (3.5.1) + sass-rails (3.2.6) @ ruby 2.0/2.3 - it worked

**Comment by Matt-Yorkley** [comment] 2017-08-04 13:40
sass 3.3
sass-rails 3.2.3

**Comment by Vasfed** [comment] 2017-08-04 13:58
@Matt-Yorkley 
Still works with these versions, can please you provide a minimal example that fails?

**Comment by Matt-Yorkley** [comment] 2017-08-04 14:19
Here's my Gemfile: https://github.com/Matt-Yorkley/openfoodnetwork/blob/45bae55ab5d6a5be582d6449622da5f366aef734/Gemfile

**Comment by Vasfed** [comment] 2017-08-04 16:07
@Matt-Yorkley it must be some local issue, cloned your app at 45bae55ab5d6a5be582d6449622da5f366aef734 and it works (rvm ruby 2.1.5p273, but without Zeus - try killing it, may be you have some old gems preloaded there)

**Closed** 2017-08-08 11:14 UTC
